version: "3"
services:
  jenkins:
    build:
      context: "./jenkins/"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - jenkins:/var/jenkins_home jenkins
    container_name: "jenkins"

volumes:
  jenkins:
